index.html
pointerlock.js

New extension: Pointerlock

---

files.js
index.html

which opens a modal that looks like this (design temporary, known to be ugly) because we can't reliably open an input dialog without user interaction

New extension: File read and download

---

files.js

Closes https://github.com/TurboWarp/extensions/issues/28

files: Add option to show file selector immediately

---

cursor.js

Source:  https://github.com/Samq64/scratch-extensions
It's just a test extension I made a while back and thought I would add it here in case someone finds it useful.
Tested locally, everything works except the cursor reporter is blank until running one of the other blocks.

Mouse Cursor Extension

---

gamejolt.js

- added documentation, but it's still lacking examples and error descriptions, don't expect much
- added indents between block sections
- added 3 new blocks:
- automatic login
allows for automatic login after logout, which wasn't previously possible
- autologin boolean
allows to check if automatic login is available, different from GameJolt boolean since GameJolt allows guests to play games
- logged in user's username reporter
allows for the following:
which was previosly possible only after manual login with input username saved in a variable
- changed data storage get keys block, it now supports patterns, tested it, it doesn't break projects,
but in old projects it would look something like this:
is there a way to fix this?
- changed errors, they are now more accurate
- fixed data …

GameJolt API - Many updates

---

itchio.js

This can be used maliciously, but the functionality of this block is limited due to it opening windows with this:
`/purchase?popup=1`
To limit this block even further we can remove the domain argument which is replaced with default itch.io, and since this is an entire new block, nothing breaks. This won't allow users to open their game purchase popup from other websites, but there is still `☁ open window` and `☁ redirect` stuff.

Itch.io API - Got open window to work

---

extensions/files.js

files: Fix "Accepted formats:" text when using plain "open a file" block 

---

types/Scratch.d.ts

Fixes an incorrect type warning in Pen+

types: Add string to ExtensionMenu items

---

extensions/navigator.js

Closes https://github.com/TurboWarp/packager/issues/615
We're putting iPad OS and iOS into the same category: "iOS". This is consistent with Android.

New extension: Navigator Info

---

extensions/itchio.js

Fixed a bug related with returnGameSale returning nothing due to the response object always having a sale property (which is set to false if there are no sales), thus not triggering an error catch.

Itch.io API Hotfix

---

extensions/stretch.js

The old code was making sprites become quadratically larger instead of linearly larger and broke negative stretch in some situations.

stretch: Don't implement stretch multiple times per target

---

website/index.ejs

These changes are meant to give the "Copy URL" and "Open Extension" buttons more contrast and pop out more.
List of changes:
- The extension thumbnails now get blurred when you hover over them. Since the buttons are on top, this helps them stand out.
- The buttons now have a drop-shadow, which makes them easier to see on top of the background. This drop-shadow gets bigger when you hover over the buttons.

Add drop-shadow on buttons and more hover effects

---

extensions/TheShovel/profanity.js
website/index.ejs

"Bad Word Remover" is a bit more on-brand for something Scratch related, and the default value has been changed to be something nice and normal instead of something that suggests typing in a bad word
As for the image, given the Scratch Team's rules, I'd like to keep it *extremely* vague or just have it always use a placeholder image. Any image that contains words that appear to be censored is unlikely to work here

Rename the profanity remover extension and list it on the homepage

---

.eslintrc.js
development/.eslintrc.js
development/builder.js
extensions/.eslintrc.js
package.json

- ESLint rules specifically for extensions are now in the extensions folder
- Putting any extension code outside of the IIFE will now cause an error
- Any ESLint *warning* will now cause GitHub Actions to report an error. Hopefully this will encourage people to resolve style issues so that I don't need to.

Revise ESLint more

---

extensions/TheShovel/ShovelUtils.js

Small change, but I added deleteSprite into Shovel's Utilities as @TheShovel is currently working on another extension. First time making a PR here, anything strange you notice, please let me know.

Add delete sprite mechanics to Shovel's Utilities

---

extensions/navigator.js

Returns the memory of the device.
This is not supported on some browsers, so it will return "Unsupported" if so.

Add memory block to navigator.js

---

website/index.ejs

Extension still works even though it's legally ambiguous.
Hope to add it back to the homepage when these concerns are addressed: https://github.com/TurboWarp/extensions/pull/319#issuecomment-1520247431

Temporarily unlist 0832/rxFS from the homepage

---

extensions/TheShovel/ShovelUtils.js

@TheShovel
When importing costumes or sounds, if the name was not a string, after saving the project and trying to open it, it would fail to open. https://scratch.mit.edu/discuss/topic/681755/
This PR fixes this issue with the first commit.
The second commit changes default sound link since the old one no longer works.

ShovelUtils: Cast imported asset names to strings to avoid corrupting projects

---

extensions/CST1229/images.js

Updated port of the plugin-based https://cst1229.github.io/files/extensions/unsandboxed-images.js. 
Lets you display images from a URL, kinda like Pen+ but costume-based.
(Sometimes called Unsandboxed Images.)

New extension: Images

---

extensions/Xeltalliv/clippingblending.js

This PR:
* Deprecates and hides additive blending blocks
* Adds blocks for working with blend modes (https://github.com/TurboWarp/extensions/pull/263)
* Makes this extension affect pen (https://github.com/TurboWarp/extensions/issues/302)

Clipping and blending: blend modes and pen support

---

website/index.ejs

- Made `transition` at line 160 only apply to `filter`. Now, when you click the button, it will instantly darken instead of fading into a darkened state over 0.15s, and when navigating using a keyboard, the focus ring won't do a weird animation anymore.
- Updated active effect on extension buttons to darken them instead of making them slightly transparent.

Adjust button hover and active effects

---

extensions/Skyhigh173/json.js

- General Utils
- JSON Strings
- Array
- Advanced
- VM
- when you put reporter blocks into vm_setlist, vm_getlist, it wont work. (fixed)

update JSON extension - new blocks, labels

---

extensions/Xeltalliv/clippingblending.js

Adds 2 more blending options to the Clipping and Blending extension:
- `subtract`
Your standard subtract option.
- `invert`
Somewhat hard to explain; inverts the sprite when on a white background, and makes it normal on a black one (I would have reversed this behavior so white is normal, but I couldn't find a way to do that). Useful for making a "black-and-white contrast thing" effect.
https://github.com/TurboWarp/extensions/assets/68464103/587271ae-1f2e-44c8-9354-74a9b1f32491

clippingblending: Add more blending options

---

extensions/obviousAlexC/SensingPlus.js

hopefully temporary, but not optimistic
related to https://github.com/TurboWarp/extensions/issues/483
they don't work:
- In the desktop app
- In packaged electron projects
- In Firefox
- In most Chromium forks
- In most WebKit forks
- When offline
and the privacy aspect of sending audio to a remote server for transcription is slightly scary.

obviousAlexC/SensingPlus: Hide speech blocks

---

extensions/box2d.js

- Boolean to check the static mode of an object.
- Blocks to set/get the Angular Velocity of an object.
- The long property block has been split into 3 separate blocks. 3 more blocks have been added to set a custom value to each property, as well as to get the property's values afterwards. This has been highly requested.

Box 2D: Add 12 New Blocks

---

extensions/utilities.js

For the longest time, it's actually been called "Utlities"

Utilities: Fix typo in the name

---

extensions/LukeManiaStudios/lmsutils.js

Rename the "replace" block to better match how it functions.

LMS Utilities: Rename "Replace" block

---

extensions/ZXMushroom63/searchApi.js

in the desktop app we use search parameters for various important internal things, so as a precaution, prevent this extension from messing with things there

ZXMushroom63/searchAPI: disable in desktop app

---

website/index.ejs

it's been outdated for a week, and hopefully we will be releasing these more regularly

Remove desktop app version number from the website

---

extensions/files.js

Useful for downloading binary data that downloading as text would mess up, like PNG or zip (*hint hint*) files.

files: Add download URL block

---

extensions/godslayerakp/http.js

noticed a bug where the set values dont get given to fetch

patched value handling order

---

extensions/TheShovel/CanvasEffects.js

X and Y are usually used for position, not size.

Fix oversight in Canvas Effects

---

extensions/CST1229/zip.js
website/CST1229/zip.html

Resolves #753
whoops
(also adds a sentence about going to the root and the parent directory in the docs for the block)

CST1229/zip: fix going to `/`

---

extensions/DT/cameracontrols.js

- Actually set the camera BG value that's used in the reporter
- Disable interpolation when loading which almost completely ruins the camera

Camera Controls: Minor Fixes

---

extensions/TheShovel/ShovelUtils.js

Added a "get all sprites" reporter, 
and a "delete image named [name] in sprite [sprite]" block
Other changes.
Changed the version number to v1.4,
Added a unsandboxed error.

ShovelUtils Update.

---

extensions/TheShovel/LZ-String.js

- fix "compress [11] as [...]" returning broken output - https://github.com/TurboWarp/extensions/issues/806
- put more error handling in decompress

TheShovel/LZ-String: fix a couple errors

---

extensions/turboloader/audiostream.js

AudioStream: Fix broken input arguments

---

extensions/TheShovel/LZ-String.js

The linked page is not very useful from the perspective of people using this as a Scratch extension

TheShovel/LZ-String: remove docsURI

---

website/index.ejs

Reasons for this:
- Functionally, More Timers and Temporary Variables are very similar.
- Using data from the GMTK Game Jam, Temporary Variables was my 2nd most used extension; I, personally, use it in almost every project. I have also seen countless people use it.
- It's functionally much more capable than Cast, which is higher(?)
- My scroll wheel would thank you

Temporary Variables: Move extension next to "More Timers"

---

extensions/Lily/Skins.js

I don't remember how this value got changed, but it did at some point

Skins: Fix "restore targets with skin" block

---

website/CubesterYT/TurboHook.html
website/ar.html
website/bitwise.html
website/box2d.html
website/local-storage.html

Corrects `<span class="title">...</title>` to `<span class="title">...</span>`.

Correct closing span tag in documentation

---

extensions/obviousAlexC/SensingPlus.js
extensions/obviousAlexC/newgroundsIO.js
extensions/penplus.js
extensions/runtime-options.js

Can't promise this will still work with upcoming extension loading changes

Remove uses of window.Scratch

---

docs/bitwise.md

Fixes some problems and inconsistencies with the documentation for Bitwise since the documentation syntax was migrated to Markdown.
- Some blocks were missing
- x and y variables weren't italic
Note: Pull request changes not tested.

Bitwise docs fixes after change to Markdown

---

extensions/-SIPC-/time.js

Block, Extract () from () was broken and was returning NaN.
Grammar also fixed in some blocks

Fix grammar and block in 'Time' extension

---

extensions/docs-examples/unsandboxed/broadcast-5.js

The extension throws an error when it isn't an event.

docs-examples/.../broadcast-5: Fix blocktype

---

extensions/NexusKitten/controlcontrols.js
extensions/extensions.json

_Control the controls that control controlling the control plane with the new extension, Control Controls!_
But for real, **this extension can be used to show and hide the controls above packaged and unpackaged projects.** The block pallet:
This may seem arbitrary, since not a lot of people use the project controls packaged anyways, however there's still some utility in this, especially for debugging.
This extension should work both packaged and unpackaged, however please do let me know if you catch an error! HTML can vary quite a bit depending on how/if you package the project.
This extension runs off of CSS, so it may fit better as an addition to Custom Styles. If people agree with this, I'm happy to update this PR.

Add "Control Controls"

---

.prettierrc.json

On Windows, editors typically use CRLF by default. I don't see a reason why we should be violating platform conventions, so just let anyone use whatever (as long as it isn't mixed)

Use endOfLine: auto for prettier

---

extensions/gamejolt.js

- Promisified the requesting blocks except the ones that would become slow to extract all data from
(Planning to promisify all of them in the future and then add blocks that return everything in .json as an alternative)
- Made error messages more accurate and consistent
- Replaced indents with labels (Didn't check if that breaks compatibility)
- Some cosmetic changes in the code, also removed eslint disabling, let's see how it goes

gamejolt: various updates

---

extensions/TheShovel/ShovelUtils.js
extensions/cloudlink.js

These now require permission because we will follow redirects. Point them to alternatives that are known to be safe.

Update GitHub.io links

---

extensions/files.js

- Use the new API for stage overlays instead of overlaying the entire page
- At least the latest 2 versions of all major desktop browsers now support the input cancel event, so we can finally surface the secret option to only show a file picker and not the custom modal
- If oncancel is detected to not be supported, it will instead just always show the modal to avoid stalling the script if someone cancels the prompt
- Close file modal when project stopped (as you are now able to actually press the stop button)

files: various improvements

---

extensions/Skyhigh173/json.js

Just changed "replace item to" to "replace item with"

[JSON] Reword "replace item" block to be more consistent

---

extensions/runtime-options.js

Removed the "get" in the reporters for consistency

[Runtime Options] Rename reporters for consistency

---

extensions/TheShovel/ShovelUtils.js

Changes for consistency and clarity.
Old blockset
Proposed blockset
- Removed unnecessary capitalization where applicable
- Removed "get" where applicable (kept for the get as array function, as its a conversion of sorts)
- Reword "get list" to "get list as array" for more clarity

[Shovel Utils] Clarity and Consistency

---

extensions/gamepad.js

Just renaming the "connected" block for conciseness along with consistency with other booleans
Old block
Proposed block (with consistency example)

[Gamepad] Slightly reword "connected" block

---

extensions/text.js

Old blocks
New blocks
There was random caps on two blocks, just a change for consistency within the extension

[Text] tiny consistency change

---

extensions/box2d.js

This is mainly for clarity and consistency within itself and other extensions. This extentions specifically gets a lot of questions i'll try to hopefully alleviate with better worded blocks.
- change "setup stage <>" to "set stage boundaries to <>" makes it more clear that this is just setting bounds
- add "to" back to the older physics properties properties (set bounce <>) is now (set bounce to <>)
- the confusing "touching <>" block is now a much more clear "list sprites touching <>"
- added "to" to the set scroll block for internal consistency and global consistency

[Box2D] Clarity + Consistency improvements

---

extensions/local-storage.js

So if someone does this in a loop, for example, they wont be spammed with alerts forever
Which matters especially in the desktop app as it won't give you an option to disable alerts for the site

local-storage: wait a few seconds between each namespace warning

---

extensions/Skyhigh173/json.js

old blockset
new blockset
- made booleans internally consistent with missing question marks
- removed "get" where applicable
- made some blocks be more internally consistent when it comes to value order, like putting the array before the new value
- removed unnecessary words like "content" in the list block

[JSON] rewordings consistency and clarity

---

docs/TheShovel/ShovelUtils.md

The default URL in the extension was changed over a month ago (https://github.com/TurboWarp/extensions/commit/f8182b10b98d5fbb6f57d97c4dbb3c76db12f46a) and the link that's currently there does not work

TheShovel/ShovelUtils: fix link in docs

---

docs/CST1229/zip.md

Garbo's html->md conversion might have been a bit sloppy.
- Make the "File info blocks" heading sentence case
- Make 2 of the reporter blocks actually reporters

CST1229/zip: very minor docs fixes

---

extensions/utilities.js

Resolves [#Clamp bug](https://discord.com/channels/837024174865776680/1168243452899774494)
For some weird, inexplicable reason that I do not know why it happens, ArgumentType.NUMBER arguments are auto-casted to number, but _only_ if a costume with that name does not exist.
This breaks a few math-related blocks in Utilities under specific circumstances (for example, `clamp 30 between 25 and 100` returns `25` if costumes named 25 and 100 exist).
This PR fixes that, by casting the arguments to numbers in `clamp` and using Scratch.Cast.compare on `isLessOrEqual` and `isMoreOrEqual`. `exponent`'s arguments are also casted now just to be safe.

utilities: fix some blocks breaking if specific costumes exist

---

docs/gamejolt.md
extensions/gamejolt.js

- Added docs.
- Replaced some blocks with more efficient ones, replaced blocks marked as deprecated.
- Added batch blocks.
There isn't any way to independently test them without a game so we'll need people that are devs on GJ,
here are the [api docs](https://gamejolt.com/game-api/doc), they cover what fields and params namespaces have, and the extension got rest of the URL construction covered.
- Added debug mode and debug blocks, debug mode solves error messages being interpreted as a valid response, on by default to prevent significant block behaviour change.
- Unwrapped some resolves to put the error message into `err.last` for the `Last API error` block to work properly, solves people improperly using non-returning blocks and telling me that the extension is not working instead of …

gamejolt: major update

---

extensions/true-fantom/math.js

Resolves #888
- Clamp restricts the outputted number between a certain range. This block was copied from the unlisted Math and String extension. Its new home in the _listed_ Math extension is much more accessible.
- Map (scale) maps a number to a range and then scales that range to a second range.

Add clamp and scale blocks to Math

---

extensions/cloudlink.js

^
This is a critical bugfix that restores functionality for projects that rely upon the username block for obtaining user objects. This also fixes a connection timing bug.
(ignore the commit summary saying 0.1.0 - I was a little trigger happy)

Update CloudLink to v0.1.2

---

extensions/encoding.js

btoa() errors on Chinese characters. The extension should be modified to actually support those properly, but for now not translating apple will avoid an error for Chinese users
https://github.com/TurboWarp/extensions/issues/1166

encoding: Don't translate apple

---

extensions/Lily/CommentBlocks.js

Allow the reporter block to be used anywhere to circumvent using couplers. Mild convenience.

Comment Blocks: Minor change

---

docs/box2d.md
extensions/box2d.js

Resolves #1171
Might resolve #925?
Adds 3 new blocks to the Box2D Physics extension:
Disables physics for the sprite.
Sets (or gets) the simulation rate; for example, you can set it and the project's framerate to 60 to make the physics run at 60FPS.

box2d: disable physics and simulation rate blocks

---

extensions/Lily/ClonesPlus.js
extensions/Lily/LooksPlus.js
extensions/Lily/MoreEvents.js
extensions/Lily/SoundExpanded.js
extensions/NexusKitten/controlcontrols.js
extensions/NexusKitten/moremotion.js
extensions/Xeltalliv/clippingblending.js
extensions/lab/text.js
extensions/obviousAlexC/SensingPlus.js
extensions/true-fantom/math.js

With the introduction of High Contrast mode, extensions like Looks Plus should use the actual category colours by default so their high contrast colours match.

merge-upstream / use actual category colours when applicable

---

extensions/files.js

Affected browsers:
- Android WebView in mark.via (92.0.4515.105)

fix: downloadBlob isn't working properly on some old browsers

---

extensions/DNin/wake-lock.js

Resolves #1120
Currently, if you request a wake lock with the Wake Lock extension and then navigate away from the page, the wake lock gets released in the background because wake locks are automatically released when the document gets hidden, plus, the extension isn't aware of when this happens, so you have no way of knowing. 
This change makes the extension automatically request another wake lock when the document regains visibility after having been hidden. It still reports to the project that the wake lock is enabled when this happens, therefore projects will act like nothing happened but the wake lock will still be there as long as you come back. I also considered the possibility of projects enabling or disabling wake lock when the document is hidden and now handle it properly.
I …

Reacquire wake lock as needed

---

extensions/box2d.js

This PR makes the Box2D extension create boundaries around the stage size when the stage size is (re)set to boxed, instead of using set sizes and positions for a 480 pixel by 360 pixel stage. For the floor stage type, it scales the floor width, since the floor was originally always 5000 units in width which could make stages 5000+ pixels in width not have a full-width floor.
It also adds comments where the stage type is set to explain the code and numbers. I think it could be useful since it took me many moments to figure out what the magic numbers meant.
**New Constants**
```patch
- bodyDef.position.Set(0, 1000 / zoom);
+ bodyDef.position.Set(0, (stageBounds.top + 820) / zoom);
...
- fixDef.shape.SetAsBox(10 / zoom, 800 / zoom);
+ fixDef.shape.SetAsBox(10 / zoom, (stageHeight + 820) / …
```

box2d: support custom stage size

---

extensions/true-fantom/couplers.js
extensions/utilities.js

I've seen multiple people want this now.

Various: allowDropAnywhere on some ternary operators.

---

extensions/gamepad.js

closes https://github.com/TurboWarp/extensions/issues/324
closes https://github.com/TurboWarp/extensions/issues/1011
closes https://github.com/TurboWarp/extensions/issues/1279
some internal changes make https://github.com/TurboWarp/extensions/issues/75 more viable in the future

gamepad: Make the deadzone circular and customizable, remember the previous direction

---

development/homepage-template.ejs
images/README.md

- Corrected it to say veggiecan/longmanDictonary **.svg** => **.png** 
- Removed the link to my github profile
- Changed the "created by" from **veggiecan** => **Veggiecan0419** (like it is for browser fullscreen)
- Updated the "developer documentation" link

A few fixes

---

CONTRIBUTING.md

Microsoft Bing Chat was rebranded to Copilot and Google Bard was renamed to Gemini.

Update the AI models' names

---

extensions/Lily/Skins.js

Fixes the bug where "delete all skins" or "delete skin ()" blocks don't work/pause when there are skins named with just numbers

Lily/Skins: fix skins with number-only names

---

extensions/obviousAlexC/penPlus.js

Didn't factor in renderer.dirty when switching draw regions.
A penguinmod user alerted me of this.

obviousAlexC/penPlus: fix missing renderer.dirty = true

---

extensions/.eslintrc.js

`vm` is already banned as it is not in globals, but window.vm was a workaround. Happens in practice in https://github.com/TurboWarp/extensions/pull/1336

Don't use window.vm

---

extensions/NOname-awa/more-comparisons.js

Almost every block in this extension has subtle inconsistencies but we can't fix a lot of them because that could break projects.
All of the less than / greater than / between blocks were broken when the inputs were strings. This is a pretty clear bug so we can change it without worrying about breaking things that weren't relying on objectively broken behavior.

NOname-awa/more-comparisons: fix a lot of bugs

---

extensions/clipboard.js

May resolve [a recent conversation in the TurboWarp Discord server](https://discord.com/channels/837024174865776680/1132437506655268926/1215424597730787368)
In some cases, the Clipboard extension's `clipboard` block can return undefined. The most reproducible case I could find is using a browser that supports the block (e.g Chrome), accepting TurboWarp's clipboard permission prompt but *denying* the *browser's* clipboard permission prompt. 
This PR should fix it. (At least, it fixes the reproducible allow+deny behavior.)

clipboard: fix clipboard block's result being undefined sometimes

---

CONTRIBUTING.md
README.md
extensions/CubesterYT/KeySimulation.js
extensions/battery.js
extensions/bitwise.js
extensions/clouddata-ping.js
extensions/cursor.js
extensions/fetch.js
extensions/files.js
extensions/gamepad.js
extensions/iframe.js
extensions/local-storage.js
extensions/navigator.js
extensions/pointerlock.js
extensions/runtime-options.js
extensions/sound.js
extensions/stretch.js
extensions/text.js
extensions/utilities.js
licenses/MPL-2.0.txt
package-lock.json
package.json

The GPL family of licenses are not perfect. Notably they are incompatible with
the SIL OFL 1.1 used by the fonts in scratch-render-fonts. In the packager we
'statically link' all of this those fonts into one HTML file. Is that legal?
Seems like you can make an argument that it's not. Who knows. I'm not a lawyer.
MPL 2.0 is a good alternative: It's still copyleft, used by real projects,
backed by a real organization, and GPL compatible.
My own extensions/contributions are now MPL-2.0, as is recommended.
LGPL-3.0 should continue to be allowed here. Use it if you want.

Mozilla Public License 2.0

---

extensions/Longboost/color_channels.js

(Of course, the old blocks weren't removed, but just hidden from the palette.)

Longboost/color_channels: Change boolean inputs to menus

---

extensions/box2d.js

- The original extension has a BSD-3-Clause license attached, not MIT https://github.com/griffpatch/scratch-vm/blob/box2d/LICENSE
- The Box2D library uses the zlib license (already mentioned in the code, this just fixes // License:)

box2d: fix inaccurate license

---

extensions/Lily/SoundExpanded.js

Adds one *very* highly-requested feature and another probably-less-requested but still useful feature. They work pretty much as you'd expect. They were actually pretty straightforward to implement (other than start sound at requiring either function overriding or function duplication, and I went with the latter).

Lily/SoundExpanded: add play sound at and loop begin/end blocks

---

extensions/Lily/SoundExpanded.js

Lily messed up the clamping, so it used to just always set the volume to 0. This fixes it.
This also makes the set volume block be clamped to 0-100 instead of being wrapped around 0-199, which I think makes more sense and is consistent with the vanilla set volume block. Though I'm not sure if it wrapping around 199 instead of 100 (or 99) was a mistake or not, or if it'll break projects.

Lily/SoundExpanded: fix "change project volume" block

---

extensions/Xeltalliv/clippingblending.js

1. In the past, stopping the project would visually reset effects, but they were still there internally, causing clones to inherit them.
2. In the past, creating clone would always result in a clone with clipping box. If the original sprite/clone did not have it, the newly created clipping box would be represented as an empty object (instead of null), which meant all of the required values were undefined. This caused clone to turn invisible. [Originally reported on discord by @ cas_thekid](https://discord.com/channels/837024174865776680/1169100193749291008)

Xeltalliv/clippingblending: Fix effect resetting on stopping project and incorrect clipping box inheritance by clones

---

extensions/true-fantom/math.js

I've added a new boolean block that checks whether a number is in a given range.
`<A is in range B - C>`
block opcode: `is_in_range_block`

true-fantom/math: add x < y < z blocks

---

extensions/NexusKitten/sgrab.js

- Half of the blocks can use our trampoline instead
- Update default values. In particular the default username is now an account that isn't empty
- Blocks that use ScratchDB are listed separately and with a warning that ScratchDB is currently offline

NexusKitten/sgrab: deal with ScratchDB being offline

---

extensions/obviousAlexC/penPlus.js

@David-Orangemoon isPackaged can be false in the packager, is there anything wrong with doing this instead?

obviousAlexC/penPlus: don't use isPackaged

---

extensions/lab/text.js

Self explanatory (the translations need to be made + updated sorry)
This change allows us to circumvent having to reverse the math and do some stupid stuff.

lab/text: add with/without word wrap option to # of lines block

---

extensions/lab/text.js

lab/text: reflow if needed in getLinesV2

---

extensions/PwLDev/vibration.js

The `navigator.vibrate()` function isn't limited to just buzzing your phone once for a specific amount of time. You can actually use it to play a pattern where the device alternates between vibrating and not vibrating. You can learn more [on MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API#vibration_patterns).
I added a block to bring this functionality to the vibration extension.
Tested on Edge for Android.

PwLDev/vibration: Vibration pattern block

---

extensions/NexusKitten/controlcontrols.js

I added a block that can play an animation to highlight any one of the four project control buttons. It can be useful to make buttons that you want the user to click pop out more, and to create effect.
Some examples:
https://github.com/TurboWarp/extensions/assets/106490990/c84efa9f-5f64-425e-b1bb-ff7bed3e9b32

NexusKitten/controlcontrols: Highlight block

---

extensions/NexusKitten/controlcontrols.js

this feature only works in Firefox and actually isn't needed anyways

NexusKitten/controlcontrols: remove revert-layer

---

extensions/Lily/AllMenus.js

Related to https://github.com/TurboWarp/extensions/issues/1530
XML escaping prevents extension from breaking if menu opcodes have weird characters but should not have any actual security impact since this is Blockly XML. It doesn't get fed directly into innerHTML = ...

Lily/AllMenus: hide unused More Events menu and XML escape

---

extensions/Xeltalliv/clippingblending.js
extensions/ar.js

I accidentally added translate functions to four menu options. I was supposed to fix these hours ago, but I fell asleep at my PC from my previous all nigther and missed updating the previous PR before you merged.

Fix Mistake

---

extensions/penplus.js
package.json

Resolves #1551
This adds `BSD-3-Clause` to the `package.json`.
I didn't add the license text into `licenses/` because none of the TurboWarp extensions contributors wrote code that they voluntarily released under a BSD-3-Clause license and all code that has a BSD-3-Clause includes a comment with the license text, but let me know if you want me to add that, or anything else for that matter.

Add BSD-3-Clause to licenses

---

development/build-production.js
development/builder.js
development/colors.js
development/compatibility-aliases.js
development/fs-utils.js
development/get-credits-for-gui.js
development/parse-extension-metadata.js
development/parse-extension-translations.js
development/render-docs.js
development/render-template.js
development/server.js
development/validate.js
eslint.config.js
package.json

Breaks the extension build process for the desktop app
There was no benefit anyways aside from esm seemingly being the future. Also the lack of a synchronous import() is rather disastrous
Reverts TurboWarp/extensions#1564

Revert "Migrate to esm"

---

docs/Xeltalliv/simple3D.md
extensions/Xeltalliv/simple3D.js

Adds support for SharkPool's "Layer Control" extension.
Fixes bug where it was always using centroid interpolation for `v_color`.
Fixes [set clear color R:() G:() B:() A:()] to take premultiplied alpha into a count. 
Adds 2 new blocks.
Adds new blending mode for drawing behind what is already drawn.
Adds ability to measure text's horizontal advance distance, which is different from text's bounding box width.
Adds Math.ceil to text borders to prevent text from jumping around when smoothly scaling border.
Adds PenguinMod and Snail IDE extension removal support.
Clarifies which parts are MPL-2.0 and which are BSD-3-Clause.
Changes default near plane to be further to reduce Z-fighting.

Xeltalliv/simple3D: Feature update v1.1.0

---

docs/steamworks.md

notably, document that macOS support is only useful for development because of the notarization requirement

steamworks: docs update 2

---

extensions/CST1229/zip.js

For developers who want to add support for this extension (like Files Expanded and arrayBuffer)
(Pen Plus v7 already does this so I assume it's okay?)

cst1229/zip: expose extension object

---

extensions/Lily/LooksPlus.js
extensions/Lily/lmsutils.js

- restore content block: do nothing if the costume wasn't changed
- remove unnecessary emitTargetsUpdate
- try/catch invalid SVGs

Lily/LooksPlus: Optimize restore content block

---

extensions/encoding.js

Fixes https://github.com/TurboWarp/extensions/issues/1166
Previously, encodings outside the Latin range were not supported.
[Base64 - "The Unicode Problem"](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)

encoding: Fix unicode base64 encode/decode

---

extensions/Skyhigh173/json.js

The function returns false when valid checked JSON is not whitespace-trimmed. Made it check parsed type.

Skyhigh173/JSON: fix json_is_valid()

---

extensions/Lily/Video.js

Official PR from me, original: https://github.com/TurboWarp/extensions/pull/1536

Lily/Video -- Clamp Volume Between 0 and 1, & Add "get frame of video at (seconds)"

---

extensions/Lily/Assets.js

sb3fix will recover it enough to load but assets will become ?. time to fix the root problem
possible root cause of https://github.com/TurboWarp/sb3fix/issues/24

Lily/Assets: fix addCostume corruption

---

extensions/mbw/xml.js

- Fixes type error in `setTextContent`
- Makes querySelector related blocks also be able to get their parent - e.g. querying `a` on `<a />` will return the expected result
- Adds "inner elements of" and "set inner elements of" blocks for interacting with innerHTML
<details><summary>Report this is based on</summary>
</details>

mbw/xml: fix bugs, add inner HTML blocks

---

extensions/Xeltalliv/clippingblending.js

https://github.com/TurboWarp/scratch-render/pull/11 changed [this](https://github.com/TurboWarp/scratch-render/commit/ed45bcdac86c83142cec1b519ec5f73a268c6f93#diff-48a7fca714b38b77f34e557a84780eab06fba6f2c8b6026b4cdf0279d1635485L250-R271) which broke Clipping & Blending that relied on [this](https://github.com/TurboWarp/extensions/blob/9edfed5e340847c61521ce9e9cbe72190553fb6f/extensions/Xeltalliv/clippingblending.js#L223)
This problem broke the sample project which divides the screen in 4 parts.

Xeltalliv/clippingblending: Fix compatibility with instanced pen rendering

---

extensions/Lily/Skins.js

The code intended to delete the skins from the renderer when running the "delete all skins" block, but since it tried to iterate through the object like an array instead of iterating through the keys, it didn't work.
This fixes a memory leak in the Skins extension.
(Also changes the `createdSkins` variable from an array into an object, since it's used with string keys.)

Lily/Skins: fix `delete all skins` not deleting the renderer skins

---

extensions/files.js

Reverts TurboWarp/extensions#1257.
Adding a delay to `revokeObjectURL` didn't help at all, as the original issue was caused by an internal bug of `mark.via`.
They have fixed the issue in later versions.

Revert "fix: downloadBlob isn't working properly on some old browsers"

---

.github/workflows/deploy.yml

Resolves these warnings from https://github.com/TurboWarp/extensions/actions/runs/11374283156/job/31642649008
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/deploy-pages@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "github-pages".
> Please update your workflow to use v4 of the artifact actions.
> Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update GitHub Actions workflows

---

extensions/obviousAlexC/newgroundsIO.js

This can cause weird issues where the medal ID is a string and therefore technically does not exist:
This also fixes the input type from STRING to NUMBER since the other block for medals uses NUMBER as well.

NG: Cast medalID inputs for medal arguments

---

docs/Xeltalliv/simple3D.md
extensions/Xeltalliv/simple3D.js

**This update:**
Changes the way bone transforms blocks handle cases when not supplied all the necessary data or the data mismatches in length. Technically not backwards compatible, but considering both the fact that no-one seems to know how to use this and the fact it only changes what happens when the feature is misused, this should be fine.
Makes bone transforms inheritable, which they weren't due to an oversight.
In the documentation adds an external link to the tutorial.
Adds a block for limiting amount of drawn instances.
Adds 2 blocks for specifying and clearing viewport, clipping and pixel readback boxes.
Adds 3 new options into mesh property reported for estimating VRAM usage.
Adds a warning for exceeding vertex index limit.
Speeds up m4.js
Removes unnecessary screen refreshes. …

Xeltalliv/simple3D: Feature update v1.2.0

---

extensions/XeroName/Deltatime.js

If projects do things like "5 / delta time", they'll break horribly when delta time is 0, so let's not return that.

XeroName/Deltatime: dont return dt=0

---

extensions/Lily/ClonesPlus.js

Resolves: https://github.com/TurboWarp/extensions/issues/1758
Now it works packaged and when opening projects :)

Lily/ClonesPlus.js -- Fix "when I start as..." Performance, but this time it works

---

extensions/Lily/TempVariables2.js

Please read the comments I put on the git commit for why stuff was changed.
As per what cst1229 did, for letting others have access to the extension stuff then lets us access the previously accessible runtime variables from another extension.
And the rest is just some minor code changes.

Expose tempvars2 on the runtime & minor code changes.

---

extensions/Xeltalliv/simple3D.js

Reported on Scratch by -Clickertale_2-.
It broke in the previous update.
[Demo project](https://turbowarp.org/editor?project_url=https://xeltalliv.github.io/simple3d-extension/examples/projects/extSkins/blocks.sb3)

Xeltalliv/simple3D: Fix unset 'readbox area' not working

---

development/builder.js
package.json

for https://github.com/TurboWarp/desktop/issues/1094 https://github.com/TurboWarp/desktop/issues/1095 maybe something else later

Include all resources in desktop app and export Builder

---

eslint.config.js
extensions/Lily/TempVariables2.js

Safari 13 and 14 have enough users that they show up in the top 100 user agents on clouddata.turbowarp.org so I'd like to keep as much alive there for as long as possible. Thus avoid using ??= (Safari 14) or Object.hasOwn (Safari 15.4).
Also includes ESLint rules, so that these are detected automatically moving forward
`ext_${extensionId}` is also a turbowarp convention not a Scratch convention
Probably at some point it makes sense to just adopt babel and transpile this stuff down to Safari 12 but for now, avoiding significant transformations is nice

Lily/TempVariables2: nitpicking

---

extensions/Xeltalliv/simple3D.js

the pen+ V7 docsURI button won't ask for permission so it doesn't make sense for this button to ask either

Xeltalliv/simple3D: don't ask for permission to open extra resources

---

.github/workflows/deploy.yml

Environment protection rules actually made the original version safe, so remove the comment saying that this condition made it safer
Leaving the condition there, so people don't start accidentally publishing a website if they fork the repository and enable actions to format their code

Security risk was already fixed by environment protection rules

---

.github/workflows/format-pr.yml

Commits pushed by the default token will not cause more workflows to run, so its commits are left in limbo forever.
FORMAT_PR_DEPLOY_KEY is an SSH key I generated. The only copy of its private key is in github actions secrets.

Use SSH deploy key for issue_comment workflow

---

extensions/-SIPC-/recording.js
extensions/files.js
package-lock.json

https://github.com/TurboWarp/scratch-gui/issues/969

Check Scratch.canDownload before downloading files

---

.github/workflows/format-pr.yml

Deploy key's write access is limited to TurboWarp/extensions, can't touch forks. Instead it now uses a PAT which I've tested to have the necessary permissions
Comment explains why the default workflow token isn't sufficient.

Use a service account PAT for format workflow

---

development/homepage-template.ejs

This just changes the colors of a few buttons and adds a faint shadow to the text on those buttons to make it easier to read the text.
Before/after:

More legible text on colored buttons

---

extensions/0832/rxFS.js
extensions/0832/rxFS2.js
extensions/extensions.json

- Delete blocks leave holes in the arrays, breaking other blocks
- The search block has been broken this entire time (`.indexOf(...) == undefined` is always false). It's not clear what it's even supposed to do, so just hide it.

0832/rxFS: fix delete block, hide search block

---

.github/workflows/label.yml

Since it doesn't actually clone the repository, have to explicitly tell `gh` what repository we're talking about

Update autolabeler workflow

---

extensions/text.js

Mostly so I show up first in the credits list, but also, I was the one who submitted it to the extensions gallery (unlike, say, window controls with bluedome77 or physics with griffpatch) so it could make more sense for this to be a normal credit.

text: change my credit from original to normal

---

.github/workflows/label.yml

Sometimes the apt-get install pcregrep step is very slow: https://github.com/TurboWarp/extensions/actions/runs/12873829059/job/35892109224
So replace that with a script using things that the runner already has installed

Remove pcregrep dependency from autolabeler

---

.github/workflows/label.yml

The heredoc's end delimiter needs to have no spaces before it. Easiest to just move it outside of the if statement.

Fix autolabel workflow again

---

extensions/pointerlock.js

This bug caused the mouse Y to scale improperly based on the stage width, causing decimals to appear sometimes.  This is especially noticeable with thin X stage sizes (which decrease Y sensitivity due to the bug) and thick ones (which increase Y sensitivity).

pointerlock: use stage height instead of width for mouse Y position

---

extensions/NexusKitten/moremotion.js

Advantages:
- Does essentially the same thing but with less lines of code
- Reports values between -180 and 180 instead of between -90 and 270
Kind of like #1460 but for a different extension.
Of course, the old blocks are still there for backwards compatibility.

NexusKitten/moremotion: Replace atan with atan2

---

extensions/JeremyGamer13/tween.js

JeremyGamer13/tween: Fix Pause button not suspending Tweening

---

extensions/Lily/MoreTimers.js

This prevents the More Timers extension from being thrown off by system clock changes.
Tested, no breaking changes.

Lily/MoreTimers: Don't rely on system clock

---

extensions/Lily/Cast.js
extensions/Lily/TempVariables2.js

Lily/Cast: Just return typeof. Lily/tempvars2: Add final missed credit.

---

docs/CubesterYT/KeySimulation.md
extensions/CubesterYT/KeySimulation.js
extensions/Lily/MoreEvents.js

| Old | New |
|--------|--------|
| `without waiting` | and `continue` |
| broadcast `message` to `sprite` | send `message` to `sprite` |

Change some block labels

---

extensions/Lily/Assets.js

This PR credits @LilyMakesThings  as well as adds 2 new blocks.
*wording changed to sprite [name,dataURI v]*
*wording changed to project [JSON,dataURI v]*
With these following blocks being merged into the menus

Lily/Assets: Add credit and new blocks

---

.github/workflows/format-pr.yml

It doesn't work because the commits are made with one of the temporary GitHub Actions tokens, causing them to end up in limbo forever since GitHub Actions doesn't run on commits made by GitHub Actions' own tokens.

Remove workflow-dispatch support from format-pr workflow

---

extensions/true-fantom/math.js

sorry mio
In Scratch/Turbowarp, the sin/cos/tan/asin/acos/atan blocks don't return as expected-- they're run through several other equations to deal with rounding, and to make the blocks compatible with degrees. 
While this makes the blocks more user-friendly, it can be annoying for people who want the original functions to have to essentially undo the extra calculations. This PR adds a new block to the Math extension which introduces a new block, featuring all the same trig functions, but returning exactly what their Javascript Math counterpart does.

true-fantom/math: Add true sin/cos/tan block.

---

extensions/true-fantom/math.js

continuation of https://github.com/TurboWarp/extensions/pull/1980, everything from there applies except:
- ctrl + f replace every time I said "normalize" with "sign of"
- block code was changed a bit because apparently there's a math function to get sign (how am i just now learning of this)

true-fantom/math: Add "sign" block

---

extensions/text.js

I fixed the Text extension to use the Scratch.Cast.* API, as specified in #1810.
This is similar to part of the pull request #1990, where the same idea was proposed.
I may have made some mistakes during my review of precedent regarding this matter, so please alert me if I got something incorrect.

Update Text extension for casting compliance under new guidelines

---

development/docs-template.ejs
development/render-docs.js

Let's try this again.
This makes documentation alerts case-insensitive.
This is the easiest solution and is better than requiring all caps, as the latter breaks the alert's title and formatting.
Putting HTML into block alerts has extra padding due to empty auto-generated `<p>` elements, planning on fixing whenever I can

Documentation Alerts bug fixing 

---

extensions/Skyhigh173/json.js
extensions/utilities.js

Fixes these reported by @Tacodiva:
No clear security impact, but these are still bugs

Fix weird object accesses in utilities, JSON

---

extensions/Lily/ClonesPlus.js

https://github.com/TurboWarp/extensions/commit/5825ea724fe303963adb8aa4af75ce75094bd38f
This change breaks projects made with previous versions of the extension. This is was a change in functionality!
One of my projects is affected by this change, because it is built with clones starting with empty local variables in mind. This should be handled differently. I dont know how this was approved. You cant change stuff like this after such a long time of them working this way, without making sure that old projects are unaffected

Lily/ClonesPlus: revert breaking change

---

extensions/Lily/Video.js

Resolves https://github.com/TurboWarp/extensions/issues/2033
Let the video's volume be affected by the project's volume (which can be manipulated through Scratch Addons and Sound Expanded).
The "volume of video" reporter has been updated to only return the video's personal volume, and does not take into account the project's volume.
https://github.com/user-attachments/assets/31dc0dca-23c2-488e-8ca0-a4725315e845

Lily/Video: Update volume functions to interact with the project volume

---

extensions/Lily/Skins.js

This causes a lot of errors if it happens repeatedly and can lead to project corruption if handled incorrectly.
This fixes some of thoes loading bugs. fixes: #2127
The issue arises from the fact that you can rename / delete / cancel the loading of a costume / skin while its still loading, and the renderer throws and error if that happens at a bad time, Skins doesnt handle this, this aims to fix that issue

Lily/Skins: Fix some fatal loading bugs.

---

extensions/Lily/Skins.js

this fixes an oversight in the old PR where some svgs may not have the right data, causing a goofy error

handle the rotationCenter error differently

---

extensions/Xeltalliv/simple3D.js

Fixes performance issue in https://github.com/TurboWarp/scratch-gui/issues/1026
Relies on https://github.com/TurboWarp/scratch-render/commit/1ffefcf2cdff2fcbe0bc7f0f000521ae2843f3a8

Xeltalliv/simple3D: mark drawable as non-interactive

---

extensions/Xeltalliv/clippingblending.js

This:
* Fixes compatibility with canvas having alpha, without changing behavior of  _any_ old projects compared to how they used to work (at least in theory).
* Sorts out long standing issue of some blending modes working incorrectly, by deprecating old block and making a new one, where everything is done in a corrected and clean way.
* Adds new blending modes, to provide proper solutions to what was done through bugs.
* Adds API, so that [Shaded](https://pen-group.github.io/extensions/) extension can be compatible with this extension, without the need for maintaining a custom fork of it.
* Adds a label explaining why there is sometimes no blocks in the palette.

Xeltalliv/clippingblending: Fix canvas alpha compatibility and other changes

---

extensions/SharkPool/Camera.js

Iterating over _allDrawables causes performance problems, example in an unrelated extension: https://github.com/TurboWarp/extensions/issues/1153
Code is similar to https://github.com/TurboWarp/scratch-render/commit/2f24d177ebe39d92fcfca88d5d2c0cc01c4d2205

SharkPool/Camera: improve performance after many drawables created and deleted

---

development/build-production.js
development/builder.js
development/colors.js
development/compatibility-aliases.js
development/download-translations.js
development/fs-utils.js
development/get-credits-for-gui.js
development/parse-extension-metadata.js
development/parse-extension-translations.js
development/render-docs.js
development/render-template.js
development/server.js
development/transifex-common.js
development/upload-translations.js
development/validate.js
eslint.config.js
package-lock.json
package.json
tsconfig.json

overdue
problem last time was that the desktop app used to import this repo as a submodule and wouldn't have the dependencies. it since was changed to be an npm dependency which fixes that

Convert development tools to ESM and update dependencies

---

extensions/extensions.json
extensions/lab/face-sensing.js

Closes https://github.com/TurboWarp/extensions/issues/880
Still a lot to do.
- I'm developing against the Scratch Lab version. Not sure if they changed anything in the version that will get released.
- Still need to figure out how large external libraries will be handled. Being forced to figure that out now.
- Need to verify that performance impact is minimal, probably add some throttling to keep in line with the Scratch Lab version.
- Blazeface doesn't directly tell us some things like how titled the head is or where the top is after accounting for rotation. I wrote some of my own estimators for those that seem to closely match Scratch Lab, at least on me.

Face sensing
