TurboWarp/extensions

- bitwise.js
- bitwise_math.js
- index.html
> Add extension 'bitwise.js'

- cloudlink.js
https://github.com/mikedev101/cloudlink
> Add extension: Cloudlink 4

- gamepad.js
- Menus for buttons & axes
- New block: is gamepad connected?
- New block: get direction of axis group
- New block: get magnitude of axis group
> Update gamepad extension

- CONTRIBUTING.md
- LICENSE
Closes https://github.com/TurboWarp/extensions/issues/20
> Add LICENSE

- files.js
- pointerlock.js
These extensions should complain loudly if they are run in a sandbox for any reason
> Add missing sandbox checks

- index.html
Too much happening in the Scratch world and personal world. Releasing this around Monday is no longer viable.
> Delay intended release by 1 week

- gamepad.js
All button and gamepad inputs now have an "any" option.
> gamepad: Add "any" option for button and gamepads

- files.js
Added for https://github.com/TurboWarp/extensions/issues/28#issuecomment-1312626402
Hidden because of https://github.com/TurboWarp/extensions/issues/28#issuecomment-1312609207 so you need to use join blocks to get it
> files: add only-selector mode

- index.html
> Unsandboxed extensions are now GA

- runtime-options.js
Allowing getting and modifying turbo mode, interpolation, framerate, high quality pen, stage size, etc.
> Add runtime options extension

- itchio.js
Window declaring removal was somehow breaking the extension so I've changed it from an object to a function instead
> itchio.js hotfix

- text.js
A bunch of blocks for handling and manipulating text.
> ```js
> // Modified port of an extension from a mod I worked on.
> ```
> Add extension: Text

- stretch.js
probably not the best way of making it work
> Stretch (scale x and y) extension

- stretch.js
> Preserve stretch when cloned

- gamepad.js
Fixes https://github.com/TurboWarp/extensions/issues/71
> gamepad: Explicitly cast axis to number before adding 1

- README.md
- development/server.js
- index.html
- package-lock.json
- package.json
- Local development server, lays groundwork for more improvements
- Closes https://github.com/TurboWarp/extensions/issues/69
- Add stretch and clouddata-ping to the website
> Website and development updates

- images/README.md
> Update image attribution page

- development/build-production.js
- development/builder.js
- development/server.js
- website/index.ejs
In the desktop app, the "Open Extension" button will instead be an "Add Extension" button
> Add desktop app specific build environment

- extensions/cursor.js
- extensions/files.js
- extensions/pointerlock.js
- extensions/sound.js
routine revisit after @turbowarp/types update
> Fix some type checking errors

- development/builder.js
> All full support for extensions in subdirectories

- extensions/penplus.js
Changelog:
Added Line blocks
Fixed Color Blocks
Seperated Blocks into catagories just so I could edit them in the future without having to dig through a large blocks array! Fixed support for the Plugin Loader
Made cross platform with the same file by using conditional assignments! Confirmed some doubts (see line 52) 
Learned that javascript had C++ like conditional assignments Depracated spacial transformation block
Added spacial changing block
Other various small fixes
> Update penplus.js to version 5

- extensions/files.js
Adds a block that outputs data url for files.
> Block to output data uri for media files

- extensions/utilities.js
> New line block

- extensions/utilities.js
Forgot to push before merging https://github.com/TurboWarp/extensions/pull/179
> Finish newline character

- extensions/TheShovel/ShovelUtils.js
- extensions/TheShovel/ShovelUtilsTW.js
TurboWarp version of my misc utilities extension.
It includes:
-Blocks for importing/loading stuff from links
-Blocks for setting lists to a json array, and getting their data
-And other misc blocks
> ShovelUtilsTW

- extensions/TheShovel/ShovelUtils.js
Make GetList return a proper json.
> Fix GetList

- .eslintrc.js
- extensions/TheShovel/ShovelUtils.js
- extensions/clouddata-ping.js
- extensions/cloudlink.js
- extensions/cursor.js
- extensions/fetch.js
- extensions/gamejolt.js
- extensions/itchio.js
- extensions/penplus.js
- extensions/sound.js
- extensions/true-fantom/network.js
- extensions/utilities.js
https://github.com/TurboWarp/extensions/issues/169
> Use Scratch.fetch, Scratch.openWindow, Scratch.redirect, etc.

- extensions/TheShovel/profanityAPI.js
The profanity extension, but using the Purgomalum API instead. This doesn't have to be on the website due to its nature.
> The profanity extension, but using the api

- website/index.ejs
See the issues listed in:
https://github.com/TurboWarp/extensions/issues/223
> Unlist bad word remover from the website

- extensions/docs-examples/unsandboxed/block-utility-examples.js
- extensions/docs-examples/unsandboxed/hello-world-unsandboxed.js
- extensions/docs-examples/unsandboxed/turbo-mode.js
https://github.com/TurboWarp/docs/pull/58
> Import unsandboxed docs examples

- extensions/docs-examples/unsandboxed/broadcast-1.js
- extensions/docs-examples/unsandboxed/broadcast-2.js
- extensions/docs-examples/unsandboxed/broadcast-3.js
- extensions/docs-examples/unsandboxed/broadcast-4.js
- extensions/docs-examples/unsandboxed/broadcast-5.js
Some examples for the upcoming page about hats
> Import more docs examples

- CONTRIBUTING.md
Grammar checking and clarify that people should update the year and name in license headers
> A couple more CONTRIBUTING.md updates

- website/test/bad-xml.js
Adds another hidden test extension that test a lot of variations of issues similar to https://github.com/TurboWarp/extensions/issues/241
> Add an extension to test XML escaping

- extensions/codeGIO/ExtraUtilities.js
Opening on behalf of https://scratch.mit.edu/users/codeGIO/
> Add codeGIO/ExtraUtilities extension

- extensions/files.js
These blocks have been superseded
> files: Hide old file picker blocks

- extensions/TheShovel/ShovelUtils.js
Code from https://www.growingwiththeweb.com/2017/12/fast-simple-js-fps-counter.html
> Add fps block

- CONTRIBUTING.md
- README.md
- images/README.md
- licenses/GPL-3.0.txt
- website/index.ejs
> Extension images are now GPL 3.0 only

- extensions/TheShovel/CanvasEffects.js
- website/index.ejs
Adds a bunch of canvas effects (probably my first ever stable extension)
> Canvas effects

- extensions/LukeManiaStudios/lmsutils.js
I made this update over the course of last week.
Update includes:
- Temporary Variables
- Effect value reporter
- Reporter that inverts the input to positive/negative
- Reporter that clamps a number between a minimum and a maximum
- Boolean that reports if a user is on a mobile device
- Block that reports items of an array
- Block that reports the starting character of a word in a string
> Update LMS Utilities

- extensions/runtime-options.js
apparently the extension has been clickbaiting people for a long while
https://twitter.com/AdrianH52744591/status/1648036589233139725
> Add high quality pen to runtime-options

- extensions/NOname-awa/Regular Expression.js
- extensions/NOname-awa/regular-expression.js
> Regular Expression.js

- extensions/NOname-awa/cn-number
- extensions/NOname-awa/cn-number.js
Hidden extension
I need it for my project
> Create cn-number（Hidden extension）

- extensions/LukeManiaStudios/McUtils.js
Self explanatory, it's mcutils, the best extension ever.
> Add McUtils

- extensions/encoding.js
> Block to verify if the string is Base64

- extensions/text.js
Fixes https://github.com/TurboWarp/extensions/issues/413
> text: Fix is title case

- extensions/obviousAlexC/SensingPlus.js
Most IOS browsers do not support simultaneous touch events. So you have to do a pretty hacky solution to it.
Made it so devices with more available touches also support those.
> Fix IOS touch events and add more QOL features for touch events.

- website/test/button.js
https://github.com/TurboWarp/scratch-vm/pull/137
> Button test extension

- extensions/text.js
You can now actually use Text to iterate using a regex! (Also some other random code changes, and shortens the `count number of ()s in ()` block's name to `count () in ()`)
> text: Add count regex block

- extensions/utilities.js
Add the "clamp" block from LMS Utilities into Utilities
> Add the "clamp" block to Utilities

- website/index.ejs
https://github.com/TurboWarp/extensions/issues/493
> Mention that local storage replaces any "cookie" extensions

- extensions/text.js
Closes https://github.com/TurboWarp/extensions/issues/475
> text: Add "Exactly Title Case" option

- website/index.ejs
Removed it from the gallery again
> LMS Utilities: he has to go, blud

- images/README.md
Sorry I really forgot to do this...
> Add link to last PR in Image attribution

- extensions/LukeManiaStudios/lmsutils.js
- Add toggle to show legacy blocks
- Optimise the code to make it more readable
> LMS Utilities: Adjustments

- website/bitwise.html
Fixes a small mistake regarding which blocks take in binary and applies a few other minor edits.
> Edit Bitwise docs

- extensions/mdwalters/notifications.js
Chrome-based browsers on Android, for unknown reasons, can only display notifications through service workers, which does not make any sense.
Luckily our online editor does have a service worker, so we are able to piggy-back off of it. Projects generated by the packager are not quite as lucky.
> mdwalters/notifications: Partially fix Android support

- extensions/Skyhigh173/bigint.js
- website/index.ejs
add a new extension **BigInt**.
about BigInt: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/BigInt
Blocks :
> [new extension] BigInt extension

- extensions/obviousAlexC/newgroundsIO.js
@David-Orangemoon can you see if this causes any problems?
This is mostly intended to be used in the packager where these prompts just don't exist. We may also add newgrounds.io to the always-allowed fetch list where GameJolt already resides
> obviousAlexC/newgroundsIO: Fix lint errors

- extensions/NOname-awa/graphics2d.js
> Add translations to NOname-awa/graphics2d

- images/README.md
https://github.com/TurboWarp/extensions/commit/325bfeee7439eb75e290a2b1375c08883f21506d#commitcomment-117748551
> Update an image attribution

- .eslintrc.js
https://github.com/TurboWarp/packager/issues/705#issuecomment-1593567023
> Add a couple more ESLint globals

- images/README.md
- website/index.ejs
We can tackle the extension URL problem later
> Gallery: Change my username + link

- website/CubesterYT/TurboHook.html
my bad
https://github.com/TurboWarp/extensions/discussions/601
> CubesterYT/TurboHook: typo fix

- extensions/Lily/LooksPlus.js
part of https://github.com/TurboWarp/extensions/issues/611
> Lily/LooksPlus: fix sprite menu

- extensions/Lily/LooksPlus.js
https://github.com/TurboWarp/extensions/issues/611
> Lily/LooksPlus: fix "this sprite" in clones

- extensions/codeGIO/ExtraUtilities.js
Makes the clipboard blocks in Extra Utilities function like the clipboard blocks in Sensing+ and LMS Utilities
> ExtraUtilities: Change Clipboard Blocks

- development/builder.js
with more docs pages showing up, it would make sense for search engines to be able to find them more easily
> Generate a sitemap

- extensions/Lily/TempVariables2.js
The amount of GMTK Jam submissions that had this was appalling
> Temporary Variables: Remove console log

- CONTRIBUTING.md
> Update CONTRIBUTING.md 3

- extensions/TheShovel/LZ-String.js
- website/index.ejs
It's LZ-String, but implemented in TurboWarp. Nothing else to say. It just works.
> Add LZ-String.js

- extensions/turboloader/audiostream.js
For compatibility with Turboloader projects (we'll add a default extension URL again). Won't be listed on homepage (another extension should fill that roll) Submitted with permission from original author.
> AudioStream, from Turboloader

- CONTRIBUTING.md
> Update CONTRIBUTING.md 4

- .eslintrc.js
> Add Blockly and ScratchBlocks to ESLint globals

- extensions/battery.js
- extensions/clipboard.js
- extensions/gamepad.js
- extensions/godslayerakp/http.js
- extensions/local-storage.js
> HAT -> EVENT for non edge activated blocks

- extensions/docs-examples/unsandboxed/broadcast-5.js
- extensions/docs-examples/unsandboxed/every-second.js
- extensions/docs-examples/unsandboxed/when-key-pressed-restart.js
- extensions/docs-examples/unsandboxed/when-key-pressed-stage.js
- extensions/docs-examples/unsandboxed/when-key-pressed.js
- extensions/docs-examples/unsandboxed/when-space-key-pressed.js
- extensions/docs-examples/unsandboxed/when.js
https://github.com/TurboWarp/docs/pull/79
> Update docs examples

- development/builder.js
https://github.com/TurboWarp/scratch-gui/pull/804
> Also export credits in the JSON

- development/builder.js
We only need the JS and images
> Remove unnecessary stuff from desktop build

- extensions/ZXMushroom63/searchApi.js
https://github.com/TurboWarp/desktop/pull/758 means that URL parameters are no longer load-bearing security wise
> ZXMushroom63/searchApi: Re-enable in desktop app

- website/test/loops.js
does not work yet, but will soon
- https://github.com/TurboWarp/scratch-vm/pull/141
- https://github.com/TurboWarp/scratch-vm/pull/158
> Add LOOP and CONDITION test extension

- extensions/Lily/MoreEvents.js
> Lily/MoreEvents: Credit

- extensions/DT/cameracontrols.js
See https://github.com/TurboWarp/extensions/issues/930
> DT/cameracontrols: mark as "Very Buggy"

- docs/TheShovel/ShovelUtils.md
- extensions/TheShovel/ShovelUtils.js
Gives ShovelUtils some documentation to hopefully alleviate the amount of issues coming in for it.
> Give ShovelUtils some Documentation

- extensions/Lily/CommentBlocks.js
> Lily/CommentBlocks: Add coveted C block

- extensions/Lily/TempVariables2.js
> Lily/TempVariables2: Un-comment C-Block

- development/builder.js
So we can display them in the editor
> Add docs and samples to JSON

- development/builder.js
- package-lock.json
- package.json
Switch to our fork. Right now it's just a tiny bit smaller, but we might do a bit more later.
> Switch to @turbowarp/scratchblocks again

- extensions/Lily/lmsutils.js
Android advertises itself as Android and as Linux, so check for Android first
> Lily/lmsutils: Fix operating system block on Android

- extensions/iframe.js
- website/hello.html
- update default page
- add resize behavior option
- uses new API not yet in staging to fix behavior after changing custom stage size
> Iframe fixes

- extensions/CubesterYT/WindowControls.js
closes https://github.com/TurboWarp/extensions/issues/966
> Update CubesterYT/WindowControls credits

- extensions/Lily/lmsutils.js
Android browsers do not include the word "Mobile" in their user agent
> Lily/lmsutils: Android is mobile

- extensions/pointerlock.js
> [Pointer lock] boolean consistency

- extensions/Lily/Video.js
> Lily/Video: Make the disclaimer more visually appealing.

- CONTRIBUTING.md
Example of why you shouldn't use ChatGPT: https://chat.openai.com/share/245724e7-0a3c-4001-9fef-fb72c4a4acc6
Everything except the last code block is hallucinated garbage, and even the code block is still worse than useless as it uses ScratchX so it can never be accepted here.
> Policy on AI (ChatGPT, Bard, etc.)

- extensions/CST1229/images.js
- extensions/CST1229/zip.js
- extensions/DT/cameracontrols.js
- extensions/Longboost/color_channels.js
- extensions/NexusKitten/controlcontrols.js
- extensions/TheShovel/CanvasEffects.js
- extensions/TheShovel/CustomStyles.js
- extensions/cursor.js
- extensions/godslayerakp/http.js
- extensions/iframe.js
- extensions/local-storage.js
- extensions/mdwalters/notifications.js
- extensions/vercte/dictionaries.js
> Reset various extensions when runtime disposed

- extensions/cloudlink.js
^
This PR synchronizes cloudlink.js with [cloudlink_turbowarp_0.1.0.js](https://github.com/MikeDev101/cloudlink/blob/master/scratch/cloudlink_turbowarp_0.1.0.js) and is intended to fix bugs, improve performance, simplify/unify the extension's codebase across variants and deprecate older blocks.
> Update CloudLink Extension to v0.1.0

- .gitignore
Don't know why this was never brought up earlier
> Add .DS_Store and thumbs.db to .gitignore

- extensions/qxsck/var-and-list.js
> qxsck/var-and-list: support cloud variables

- extensions/gamejolt.js
- extensions/itchio.js
"user" "game" and "secret" went untouched in the itch.io extension because they are url params
> Scratch.translate my extensions

- extensions/obviousAlexC/penPlus.js
Backport the V7 depth buffer
Backport tri drawing from V7
Fix colour bug
Fix dot and line drawing bug.
> PenPlus 6.1 Bug Fixes

- extensions/iframe.js
closes https://github.com/TurboWarp/extensions/issues/1174
> iframe: fix x/y with viewport resize behavior

- CONTRIBUTING.md
https://github.com/TurboWarp/extensions/issues/1195
Including this in the acceptance criteria wouldn't actively disallow the possibility but would actively discourage it.
> CONTRIBUTING.md: Discourage extensions that primarily focus on enabling monetisation

- extensions/runtime-options.js
> Port Blocks From Runtime Events (My Extension) to Runtime Options

- development/builder.js
- development/fs-utils.js
- development/get-credits-for-gui.js
Will be used for updating https://turbowarp.org/credits.html
> Add a script for generating credits for scratch-gui

- extensions/Lily/TempVariables2.js
- Changed the wording of some blocks
- Allowed reporters to be dropped anywhere
- Removed icon setup
> Lily/TempVariables2: Minor tweaks

- extensions/TheShovel/CustomStyles.js
Whats new:
-Multi gradient support (radial and conic) (example usage: Color Master on my gallery):
-Ability to set Question Text Color:
> Fan Requested Changes Custom Styles

- extensions/-SIPC-/time.js
- extensions/TheShovel/CanvasEffects.js
having a link will grant an image on https://turbowarp.org/credits.html
> Update SharkPool credits

- extensions/qxsck/var-and-list.js
> Var List color

- extensions/obviousAlexC/penPlus.js
got the demo on my testing chromebook running from 5fps to 15fps also got the mast on my main computer running 15 fps from 10 fps on firefox (Firefox has the weakest webgl version.)
> obviousAlexC/penPlus: optimize

- extensions/TheShovel/CustomStyles.js
resolves https://github.com/TurboWarp/extensions/issues/1290
you should merge more control, NOW! (that is a joke)
> TheShovel/CustomStyles: fix question text color

- extensions/NexusKitten/sgrab.js
Also adds a warning regarding how unreliable the depended API is.
> NexusKitten/S-Grab: Fix some responses not returning anything.

- extensions/obviousAlexC/SensingPlus.js
- extensions/true-fantom/base.js
- extensions/true-fantom/couplers.js
- extensions/true-fantom/regexp.js
> update extension i10n

- extensions/lab/text.js
- fix outline being cut off
- use rounded outline, looks a lot better
- fixed custom fonts
> lab/text: bug fixes

- extensions/obviousAlexC/penPlus.js
Accidentally was clearing the draw buffer instead of the depth buffer upon exit.
> ObviousAlexC/PenPlus : Accidentally cleared the wrong buffer

- extensions/Lily/Skins.js
> Lily/Skins: Remove "lms-" when returning current skin

- extensions/obviousAlexC/penPlus.js
I accidentally reverted things I didn't want to now that I have the TW github properly cloned this shouldn't happen again and my version should always be up to date.
> obviousAlexC/penPlus: revert accidentally reversions

- extensions/obviousAlexC/penPlus.js
sent to me by canaloupe_1 on discord
> obviousAlexC/penPlus: fix setStampAttribute

- extensions/TheShovel/ColorPicker.js
> TheShovel/ColorPicker: fix incorrect position if moved and shown in same frame

- extensions/lab/text.js
maybe later we automatically resize text that has no explicit width
> lab/text: stage width is not constant

- extensions/lab/text.js
Fixed [this](https://github.com/TurboWarp/extensions/issues/1434) issue.
> lab/text: Fixed typo

- extensions/qxsck/data-analysis.js
It's not uncommon to need the sum of a bunch of numbers.
> data-analysis: Add sum block

- extensions/lab/text.js
Actually ScratchSavers in TurboWarp but everyone calls it Scratch
It does work in Scratch Lab
> lab/text: add Scratch font

- extensions/Skyhigh173/bigint.js
> Skyhigh173/bigint: support native big int and add translations

- extensions/obviousAlexC/SensingPlus.js
runtime.isPackaged is packaged runtime mode which is a different thing and can be disabled
> obviousAlexC/SensingPlus: fix <is packaged?>

- extensions/CST1229/images.js
- extensions/extensions.json
it's merged, it works, may as well actually list it
> CST1229/images: list on the website

- docs/Xeltalliv/simple3D.md
- extensions/Xeltalliv/simple3D.js
Sorry for another PR less than 24 hours after the previous one. Both issues aren't critical, so it's okay if this takes a while to merge.
> Xeltalliv/simple3d: fix other mod compatibility, fix transform to scratch units, improve docs

- .gitignore
- extensions/obviousAlexC/penPlus.js
Also setDURIclampmode was hidden for a reason. It was unstable. Very unstable.
Fixed U_res in render textures,
Fixed bugs involving tinted triangles,
Made transparency look more like the original,
Fixed image manipulation.
> obviousAlexC/penPlus: the big ol U_res patch

- extensions/NOname-awa/graphics2d.js
Changed the "direction of _x1_,_y1_ to _x2_,_y2_" function to use Math.atan2. It does the same thing but with less lines of code.
Tested pretty much everything I can think of, atan2(0, 0) is 0, output ranges from -180 to 180, atan2 already auto-converts strings to numbers.
> NOname-awa/graphics2d: Use atan2 to get coord to coord angle

- extensions/files.js
This would slowly leak memory and break games that need to detect the escape button
> files: Fix event listener leak

- extensions/NexusKitten/sgrab.js
if we got a 404 then we shouldnt try to grab any information
> NexusKitten/sgrab: handle errors better

- extensions/Xeltalliv/simple3D.js
> Xeltalliv/simple3D: conetxt --> context

- extensions/Lily/SoundExpanded.js
fixes https://github.com/TurboWarp/extensions/issues/1355
fixes this block
> Lily/SoundExpanded: fix set volume and start looping w/ start

- extensions/Lily/MoreEvents.js
Closes https://github.com/TurboWarp/extensions/issues/1530
> Lily/MoreEvents: don't translate an unused menu

- extensions/NOname-awa/cn-number.js
did you know? apparently Chinese has a separate set of numerals used in financial contexts
> NOname-awa/cn-number: translate

- extensions/veggiecan/browserfullscreen.js
> veggiecan/browserfullscreen: no-op if no change will occur

- extensions/penplus.js
> penplus: fix description

- extensions/SharkPool/Font-Manager.js
This is a non-essential change take however long to merge this.
> SharkPool/Font-Manager: I dont go by ashime anymore.

- docs/steamworks.md
- extensions/extensions.json
- extensions/steamworks.js
also https://github.com/TurboWarp/packager/pull/880
> steamworks: extension part

- extensions/veggiecan/LongmanDictionary.js
fix https://github.com/TurboWarp/extensions/issues/1676
> veggiecan/LongmanDictionary: fix all defs returning array instead of string

- extensions/Lily/Video.js
seems to fix https://github.com/TurboWarp/scratch-render/issues/12
> Lily/Video: append the <video>s into the DOM

- development/homepage-template.ejs
To make it more... uh, professional. ✨
> Edit some paragraphs on the homepage

- extensions/Lily/ClonesPlus.js
- extensions/Lily/LooksPlus.js
- extensions/Skyhigh173/json.js
for example, extensions can be loaded while the project is still loading
should resolve https://discordapp.com/channels/837024174865776680/1285154510527922186
> Lily/ClonesPlus, Lily/LooksPlus, Skyhigh173/json: editingTarget can be null

- extensions/Skyhigh173/bigint.js
- extensions/Skyhigh173/json.js
- extensions/qxsck/data-analysis.js
- extensions/qxsck/var-and-list.js
for https://github.com/TurboWarp/scratch-gui/pull/962
> Add links for qxsck & Skyhigh173

- extensions/Lily/ClonesPlus.js
Fixes Lag spikes, makes the hat run like an event
Fixes: https://github.com/TurboWarp/extensions/issues/1758
> Lily/ClonesPlus.js -- Improve Performance of "when I start as..."

- extensions/Lily/ClonesPlus.js
Reverts TurboWarp/extensions#1759
Someone on Discord already got an issue with it. It's breaking projects.
We need this merged ASAP
CC @SharkPool-SP
You got to be kidding me, it was working for ten people, why break now??
> Revert "Lily/ClonesPlus.js -- Improve Performance of "when I start as...""

- extensions/Lily/ClonesPlus.js
Maybe tomorrow
Reverts TurboWarp/extensions#1761
> Revert "Lily/ClonesPlus.js -- Fix "when I start as..." Performance, but this time it works"

- extensions/TheShovel/CustomStyles.js
the text color does not contain "!important" so the text remains white.
> TheShovel/CustomStyles: fix text color

- development/builder.js
> Fix scratchblocks path when part of larger npm tree

- development/docs-template.ejs
so that right click > open link works
> Use full URL for read in browser button

- development/docs-template.ejs
> Use full URL for homepage link

- extensions/text.js
Partially reverts a3d9564a93e0b5dc3a5f6f4333823d33d6e175b6
> text: update credits

- .github/workflows/format-pr.yml
Not possible for issue_comment trigger to have write permissions to a pull request's branch.
> Remove issue_comment logic

- .github/workflows/deploy.yml
Fixes a hypothetical attack that has not occurred
> Restrict deploy workflow repository and ref

- extensions/Lily/ClonesPlus.js
Now it should work. It waits for variables to initialize
> Lily/ClonesPlus: re-re fix performance for "when I start as w/ set to ..." block

- extensions/Lily/ClonesPlus.js
Reverts TurboWarp/extensions#1763
https://discord.com/channels/837024174865776680/1147654296926687242/1323418005371228282
> Revert "Lily/ClonesPlus: re-re fix performance for "when I start as w/ set to ..." block"

- extensions/obviousAlexC/SensingPlus.js
- Fix touch blocks not working in Safari
- Fix accelerometer blocks not working in any browser
- Fix gyroscope blocks not working in any browser
- Fix acceleration blocks being incorrectly labeled as speed
> obviousAlexC/SensingPlus: fix several broken blocks

- .github/workflows/download-translations.yml
- .github/workflows/upload-translations.yml
- development/download-translations.js
- development/transifex-common.js
- development/upload-translations.js
- package-lock.json
- package.json
Currently workflow_dispatch, but eventually should be fully automated
> Add workflows for uploading and downloading translations

- .github/workflows/download-translations.yml
> Fix download translations branch deletion

- extensions/veggiecan/mobilekeyboard.js
Resolves #1765
Simple fix, really. I kept forgetting to make this change.
> veggiecan/mobilekeyboard: fix typed text block returning undefined

- .github/workflows/download-translations.yml
- development/upload-translations.js
- update upload translations sanity checks to be more strict
- schedule download translations workflow to run twice per week
> Update translation workflows

- .github/workflows/label.yml
- fix breakage when diff contains very long line (#1861)
- unhardcode repository
- add more logging
> Update autolabeler 2

- development/builder.js
- development/homepage-template.ejs
- development/parse-extension-metadata.js
- extensions/Lily/HackedBlocks.js
- put original author first
- allow marking extension as scratch-compatible
- mark hacked block collection as scratch-compatible
> Extension metadata updates

- docs/DNin/wake-lock.md
- docs/Lily/Skins.md
- docs/TheShovel/ShovelUtils.md
- docs/ar.md
- docs/box2d.md
- docs/gamejolt.md
Self Explanatory
Let me know if I missed anything.
> Documentation Parity Fixes

- docs/CST1229/zip.md
some things that have been bothering me for a while now, and also some parenthesis cleanup (i use them way too much)
> CST1229/zip: minor docs fixes

- extensions/NexusKitten/moremotion.js
https://github.com/TurboWarp/extensions/commit/72d6db8041b00446d71e7abb19c78119a3a8b015
- fix incorrect  comment
- dont hide point to
> NexusKitten/moremotion: fix previous commit

- extensions/Lily/Video.js
Resolves #1903 
Should we put loop in `getAttribute` or `getState`?
> Lily/Video: added "play video until done" and "loop video" block

- extensions/JeremyGamer13/tween.js
- extensions/Lily/Video.js
- extensions/SharkPool/Font-Manager.js
- extensions/Skyhigh173/json.js
- extensions/TheShovel/ShovelUtils.js
self explanatory
Adds credit to Fath11 for tweening and video
Adds myself as credit to shovelutils
Changes my name cuz its mio now 😎
> Add some missing credit

- extensions/qxsck/data-analysis.js
https://github.com/TurboWarp/extensions/pull/1907#discussion_r1945373074
> qxsck/data-analysis: Fix spread overflow

- .github/workflows/format-pr.yml
It will now leave a comment when it hits a known failure case
> Add better error handling to format-pr workflow

- extensions/SharkPool/Camera.js
Pointed out by Nameless. Thanks!
> SharkPool/Camera.js: fix speech bubble positions

- extensions/Lily/ListTools.js
Should resolve https://github.com/TurboWarp/extensions/issues/1928
> Lily/ListTools: Cast all list inputs to string

- extensions/DT/cameracontrols.js
- extensions/SharkPool/Camera.js
- extensions/extensions.json
and call the new one Camera V2
> Call camera controls "Camera V1" and list it again

- extensions/Lily/lmsutils.js
https://github.com/TurboWarp/extensions/issues/1958
> lily/lmsutils -- Implement the missing "list variables" block

- extensions/Lily/ClonesPlus.js
https://github.com/TurboWarp/extensions/issues/1421
> Lily/ClonesPlus: Fix clones of clones not inheriting local variables and other data

- extensions/Xeltalliv/clippingblending.js
> Xeltalliv/clippingblending: handle pen skin with id 0

- extensions/obviousAlexC/penPlus.js
Fixes various bugs and inconsistencies. We may need to do a small edit to the translation though that is not within my expertise.
> ObviousAlexC/PenPlus: Update Pen+ to 7.1.8

- extensions/Lily/ClonesPlus.js
context: https://github.com/TurboWarp/extensions/pull/2110
re-fixes: https://github.com/TurboWarp/extensions/issues/1421
> Lily/ClonesPlus: separate blocks for cloning myself and cloning the original

- extensions/lab/text.js
this fixes https://github.com/TurboWarp/extensions/issues/2207 once some other -render changes are live
> lab/text: implement isMetricsReady

- translations/extension-metadata.json
- translations/extension-runtime.json
This pull request was made by a robot.
> [Automated] Update translations 2025-09-13

- extensions/godslayerakp/ws.js
the old one doesn't work any more
the new one seems slow but at least it somewhat works
> godslayerakp/ws: replace default echo server

- extensions/godslayerakp/http.js
https://github.com/TurboWarp/extensions/issues/2255 https://github.com/TurboWarp/desktop/issues/1242
> godslayerakp/http: clarify blocks that operate on request headers vs response headers

- CONTRIBUTING.md
> Update CONTRIBUTING.md to say TurboWarp extensions instead of Scratch extensions
